apiVersion: v1
kind: ConfigMap
metadata:
  {{- range $key := list "DB_URL" "KAFKA_BOOTSTRAP_SERVERS" "OIDC_ISSUER_URI" "OIDC_JWK_SET_URI" }}
  {{- $_ := required (printf "config.%s is required" $key) (get $.Values.config $key) }}
  {{- end }}
  name: {{ include "risk.name" . }}
  labels:
    {{- include "risk.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
